tuote1=input("Anna tuotteen 1 hinta: ")
hinta1 = int(tuote1)
tuote2=input("Anna tuotteen 2 hinta: ")
hinta2 = int(tuote2)
print("Tuote 1 maksaa", hinta1, "e ja tuote 2 maksaa", hinta2, "e.")
print("Tuotteiden summa on", hinta1+hinta2, "euroa.")
